### ISSUE TITLE
Installation Guide

### ISSUE THREAD

**Issue by vibhi19** [dialogs/dialog-web-components#174]
I want to selfhost this Project. is there any Good installation guide ?

**Comment by meafmira** [comment]
@vibhi19 I don't understand what do you exactly mean? What do you want to selfhost? Documentation?

**Comment by vibhi19** [comment]
> @vibhi19 I don't understand what do you exactly mean? What do you want to selfhost? Documentation?

Looks like i am confused i wanted to host this https://dlg.im/en

**Comment by olegshilov** [comment]
@vibhi19 Good day. You can contact us through the form on the website or by sending an email to info@dlg.im
