### ISSUE TITLE
Cannot install dialog-web-components.

### ISSUE THREAD

**Issue by klisfer** [dialogs/dialog-web-components#180]
I have been trying to install the dialog-web-components and I have tried it both with yarn and npm but it fails with the same error message every time.

Any ideas on fixing the issue or a workaround?

`npm ERR! code E404
npm ERR! 404 Not Found: @dlghq/dialog-ui@0.0.18`

**Comment by meafmira** [comment]
@klisfer fixed

**Comment by klisfer** [comment]
It works now. Thanks

**Comment by klisfer** [comment]
After the installation the library is giving an error while importing:

export { default as Avatar } from './components/Avatar/Avatar';
^^^^^^

SyntaxError: Unexpected token export

**Comment by meafmira** [comment]
@klisfer we don't transpile components before publish for now. So you need to configure your bundle for this. Also there is an issue for this feature - https://github.com/dialogs/dialog-web-components/issues/101

We'll implement it soon
