### ISSUE TITLE
Compilation fails when running the example

### ISSUE THREAD

**Issue by arome** [dialogs/dialog-web-components#44]
Hi all,

When I try to run the usage example you have in the README.md I get the following compile error :
Failed to compile
./node_modules/@dlghq/dialog-components/src/components/Avatar/Avatar.js
Module parse failed: [...]\node_modules\@dlghq\dialog-components\src\components\Avatar\Avatar.js Unexpected token (6:12)
You may need an appropriate loader to handle this file type.
|  */
| 
| import type { AvatarPlaceholder } from '@dlghq/dialog-types';
| import type { AvatarSize } from './getAvatarSize';
| import type { Gradient } from './getAvatarColor';
This error occurred during the build time and cannot be dismissed.

When I go in the Avatar.js file I see the following error on these 3 imports ([js] 'import ... =' can only be used in a .ts file.). 

I'm running windows 10, Node v.6.10.0 and npm v.5.4.2 with the dlghq v.0.141.1.

**Comment by olegshilov** [comment]
Hi. Can you show us your webpack config? In particular the section with the settings of the babel-loader.

**Comment by nkt** [comment]
I've just added webpack configuring section to our readme. Please [check it out](https://github.com/dialogs/dialog-web-components#webpack-configuration).
If you have another questions, please open another issue.
